[main_app]
bot_token = "token-here"
owner_id = 0
admin_ids = []

[apps]


[database]
models = [ "src.database", "aerich.models",]
protocol = "sqlite"
user = ""
password = ""
host = ""
port = ""

