[app_root]
bot_token = "token-here"
owner_id = 0
admin_ids = []

[global_data]
owner_id = 0
admin_ids = []

[database]
models = [ "src.database", "aerich.models",]
protocol = "sqlite"
user = ""
password = ""
host = ""
port = ""

